[build]
  command = "pnpm --filter @spotify-music-quiz/web web:build"
  publish = "apps/web/dist/client"
[dev]
  command = "pnpm --filter @spotify-music-quiz/web web:dev"
  targetPort = 3000
  port = 8888