/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLobbyLobbyIdRouteImport } from './routes/_authenticated/lobby.$lobbyId'
import { Route as AuthenticatedStudioQuizIdRouteImport } from './routes/_authenticated/studio.$quizId'
import { Route as GuestLobbyLobbyIdRouteImport } from './routes/guest/lobby.$lobbyId'
import { Route as AuthenticatedQuizShareQuizIdRouteImport } from './routes/_authenticated/quiz.share.$quizId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLobbyLobbyIdRoute =
  AuthenticatedLobbyLobbyIdRouteImport.update({
    id: '/lobby/$lobbyId',
    path: '/lobby/$lobbyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioQuizIdRoute =
  AuthenticatedStudioQuizIdRouteImport.update({
    id: '/studio/$quizId',
    path: '/studio/$quizId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const GuestLobbyLobbyIdRoute = GuestLobbyLobbyIdRouteImport.update({
  id: '/guest/lobby/$lobbyId',
  path: '/guest/lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizShareQuizIdRoute =
  AuthenticatedQuizShareQuizIdRouteImport.update({
    id: '/quiz/share/$quizId',
    path: '/quiz/share/$quizId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/join': typeof JoinRoute
  '/lobby/$lobbyId': typeof AuthenticatedLobbyLobbyIdRoute
  '/studio/$quizId': typeof AuthenticatedStudioQuizIdRoute
  '/guest/lobby/$lobbyId': typeof GuestLobbyLobbyIdRoute
  '/quiz/share/$quizId': typeof AuthenticatedQuizShareQuizIdRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/': typeof AuthenticatedIndexRoute
  '/lobby/$lobbyId': typeof AuthenticatedLobbyLobbyIdRoute
  '/studio/$quizId': typeof AuthenticatedStudioQuizIdRoute
  '/guest/lobby/$lobbyId': typeof GuestLobbyLobbyIdRoute
  '/quiz/share/$quizId': typeof AuthenticatedQuizShareQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/join': typeof JoinRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lobby/$lobbyId': typeof AuthenticatedLobbyLobbyIdRoute
  '/_authenticated/studio/$quizId': typeof AuthenticatedStudioQuizIdRoute
  '/guest/lobby/$lobbyId': typeof GuestLobbyLobbyIdRoute
  '/_authenticated/quiz/share/$quizId': typeof AuthenticatedQuizShareQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/lobby/$lobbyId'
    | '/studio/$quizId'
    | '/guest/lobby/$lobbyId'
    | '/quiz/share/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/'
    | '/lobby/$lobbyId'
    | '/studio/$quizId'
    | '/guest/lobby/$lobbyId'
    | '/quiz/share/$quizId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/join'
    | '/_authenticated/'
    | '/_authenticated/lobby/$lobbyId'
    | '/_authenticated/studio/$quizId'
    | '/guest/lobby/$lobbyId'
    | '/_authenticated/quiz/share/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  JoinRoute: typeof JoinRoute
  GuestLobbyLobbyIdRoute: typeof GuestLobbyLobbyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lobby/$lobbyId': {
      id: '/_authenticated/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof AuthenticatedLobbyLobbyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio/$quizId': {
      id: '/_authenticated/studio/$quizId'
      path: '/studio/$quizId'
      fullPath: '/studio/$quizId'
      preLoaderRoute: typeof AuthenticatedStudioQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/guest/lobby/$lobbyId': {
      id: '/guest/lobby/$lobbyId'
      path: '/guest/lobby/$lobbyId'
      fullPath: '/guest/lobby/$lobbyId'
      preLoaderRoute: typeof GuestLobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/share/$quizId': {
      id: '/_authenticated/quiz/share/$quizId'
      path: '/quiz/share/$quizId'
      fullPath: '/quiz/share/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizShareQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLobbyLobbyIdRoute: typeof AuthenticatedLobbyLobbyIdRoute
  AuthenticatedStudioQuizIdRoute: typeof AuthenticatedStudioQuizIdRoute
  AuthenticatedQuizShareQuizIdRoute: typeof AuthenticatedQuizShareQuizIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLobbyLobbyIdRoute: AuthenticatedLobbyLobbyIdRoute,
  AuthenticatedStudioQuizIdRoute: AuthenticatedStudioQuizIdRoute,
  AuthenticatedQuizShareQuizIdRoute: AuthenticatedQuizShareQuizIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  JoinRoute: JoinRoute,
  GuestLobbyLobbyIdRoute: GuestLobbyLobbyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
