/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LobbyLobbyIdRouteImport } from './routes/lobby.$lobbyId'
import { Route as StudioQuizIdRouteImport } from './routes/studio.$quizId'
import { Route as QuizShareQuizIdRouteImport } from './routes/quiz.share.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyIdRoute = LobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobbyId',
  path: '/lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioQuizIdRoute = StudioQuizIdRouteImport.update({
  id: '/studio/$quizId',
  path: '/studio/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizShareQuizIdRoute = QuizShareQuizIdRouteImport.update({
  id: '/quiz/share/$quizId',
  path: '/quiz/share/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/studio/$quizId': typeof StudioQuizIdRoute
  '/quiz/share/$quizId': typeof QuizShareQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/studio/$quizId': typeof StudioQuizIdRoute
  '/quiz/share/$quizId': typeof QuizShareQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/studio/$quizId': typeof StudioQuizIdRoute
  '/quiz/share/$quizId': typeof QuizShareQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/lobby/$lobbyId'
    | '/studio/$quizId'
    | '/quiz/share/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/lobby/$lobbyId'
    | '/studio/$quizId'
    | '/quiz/share/$quizId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/lobby/$lobbyId'
    | '/studio/$quizId'
    | '/quiz/share/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LobbyLobbyIdRoute: typeof LobbyLobbyIdRoute
  StudioQuizIdRoute: typeof StudioQuizIdRoute
  QuizShareQuizIdRoute: typeof QuizShareQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$lobbyId': {
      id: '/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof LobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$quizId': {
      id: '/studio/$quizId'
      path: '/studio/$quizId'
      fullPath: '/studio/$quizId'
      preLoaderRoute: typeof StudioQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/share/$quizId': {
      id: '/quiz/share/$quizId'
      path: '/quiz/share/$quizId'
      fullPath: '/quiz/share/$quizId'
      preLoaderRoute: typeof QuizShareQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LobbyLobbyIdRoute: LobbyLobbyIdRoute,
  StudioQuizIdRoute: StudioQuizIdRoute,
  QuizShareQuizIdRoute: QuizShareQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
