export const GAME_CONFIG = Object.freeze({
  WS_URL: import.meta.env.VITE_WS_URL ?? 'http://localhost:3001',
  DEFAULT_GUESSING_TIME_LIMIT_SECS: 30,
  FAST_GUESS_WARNING_TIME_LIMIT_SECS: 10,
  GET_READY_COUNTDOWN_SECS: 3,
  MIN_SNIPPET_WINDOW_MS: 5000,
  DEFAULT_SNIPPET_WINDOW_MS: 30000,
  FALLBACK_SONG_DURATION_MS: 180000,
  LOBBY_CODE_LENGTH: 4,
  ACTIVE_SESSIONS_REFETCH_INTERVAL_MS: 5000,
  AUDIO_SYNC_CHECK_INTERVAL_MS: 100,
  RETRY_PLAYBACK_DELAY_MS: 800,
  DEFAULT_PLAYBACK_RETRIES: 2,
  SUCCESS_TOAST_DURATION_MS: 3000,
});

export const AUDIO_CONFIG = Object.freeze({
  DEFAULT_VOLUME: 0.5,
  MIN_VOLUME: 0.0,
  MAX_VOLUME: 1.0,
  VOLUME_STEP: 0.05,
  STORAGE_KEY: 'spotify-quiz-volume',
  SDK_PLAYER_NAME: 'Spotify Music Quiz Board',
  SDK_SCRIPT_SRC: 'https://sdk.scdn.co/spotify-player.js',
});